czno: call_vienna_rna.cpp czno_experiments.cpp czno_proposed_methods.cpp enumerate_long_stacks.cpp main.cpp misc.cpp previous_direct_methods.cpp previous_indirect_ea.cpp previous_indirect_mh1998.cpp previous_indirect_tabu.cpp previous_indirect_rna2dfold.cpp
	g++ -I ./ -std=c++1y -static-libstdc++ -O2 call_vienna_rna.cpp czno_experiments.cpp czno_proposed_methods.cpp enumerate_long_stacks.cpp main.cpp misc.cpp previous_direct_methods.cpp previous_indirect_ea.cpp previous_indirect_mh1998.cpp previous_indirect_tabu.cpp previous_indirect_rna2dfold.cpp -o czno
clean:
	rm -f *.o czno
